# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modified_final_layout.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import qdarkstyle

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(580, 662)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 340, 242, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.reg_quality = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.reg_quality.setContentsMargins(0, 0, 0, 0)
        self.reg_quality.setObjectName("reg_quality")
        self.label_sys_in = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_sys_in.setObjectName("label_sys_in")
        self.reg_quality.addWidget(self.label_sys_in, 2, 0, 1, 1)
        self.var_sysin = QtWidgets.QLabel(self.gridLayoutWidget)
        self.var_sysin.setObjectName("var_sysin")
        self.reg_quality.addWidget(self.var_sysin, 2, 1, 1, 1)
        self.label_sys_out = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_sys_out.setObjectName("label_sys_out")
        self.reg_quality.addWidget(self.label_sys_out, 3, 0, 1, 1)
        self.var_sysout = QtWidgets.QLabel(self.gridLayoutWidget)
        self.var_sysout.setObjectName("var_sysout")
        self.reg_quality.addWidget(self.var_sysout, 3, 1, 1, 1)
        self.var_regerror = QtWidgets.QLabel(self.gridLayoutWidget)
        self.var_regerror.setObjectName("var_regerror")
        self.reg_quality.addWidget(self.var_regerror, 4, 1, 1, 1)
        self.label_reg_error = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_reg_error.setObjectName("label_reg_error")
        self.reg_quality.addWidget(self.label_reg_error, 4, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 460, 551, 41))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.tuning = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.tuning.setContentsMargins(0, 0, 0, 0)
        self.tuning.setObjectName("tuning")
        self.line_13 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.tuning.addWidget(self.line_13, 0, 0, 1, 1)
        self.var_spinbox_P = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.var_spinbox_P.setObjectName("var_spinbox_P")
        self.tuning.addWidget(self.var_spinbox_P, 0, 2, 1, 1)
        self.var_spinbox_I = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.var_spinbox_I.setObjectName("var_spinbox_I")
        self.tuning.addWidget(self.var_spinbox_I, 0, 6, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.tuning.addWidget(self.line_10, 0, 3, 1, 1)
        self.label_D = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_D.setObjectName("label_D")
        self.tuning.addWidget(self.label_D, 0, 8, 1, 1)
        self.label_P = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_P.setObjectName("label_P")
        self.tuning.addWidget(self.label_P, 0, 1, 1, 1)
        self.label_I = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_I.setObjectName("label_I")
        self.tuning.addWidget(self.label_I, 0, 4, 1, 1)
        self.var_spinbox_D = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.var_spinbox_D.setObjectName("var_spinbox_D")
        self.tuning.addWidget(self.var_spinbox_D, 0, 9, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.tuning.addWidget(self.line_12, 0, 7, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.tuning.addWidget(self.line_11, 0, 5, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.tuning.addWidget(self.line_14, 0, 10, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 450, 551, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(210, 340, 20, 101))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(10, 330, 551, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(10, 550, 551, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(260, 410, 301, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.velocity_range_monit = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.velocity_range_monit.setContentsMargins(0, 0, 0, 0)
        self.velocity_range_monit.setObjectName("velocity_range_monit")
        self.button_send_velocity_update = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_send_velocity_update.setObjectName("button_send_velocity_update")
        self.velocity_range_monit.addWidget(self.button_send_velocity_update)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 300, 551, 21))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.operation_state = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.operation_state.setContentsMargins(0, 0, 0, 0)
        self.operation_state.setObjectName("operation_state")
        self.label_monit = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_monit.sizePolicy().hasHeightForWidth())
        self.label_monit.setSizePolicy(sizePolicy)
        self.label_monit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_monit.setObjectName("label_monit")
        self.operation_state.addWidget(self.label_monit)
        self.var_monit = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.var_monit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.var_monit.setObjectName("var_monit")
        self.operation_state.addWidget(self.var_monit)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(10, 290, 551, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 20, 541, 251))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 570, 551, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_start_logging = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.button_start_logging.setObjectName("button_start_logging")
        self.horizontalLayout_2.addWidget(self.button_start_logging)
        self.button_stop_logging = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.button_stop_logging.setObjectName("button_stop_logging")
        self.horizontalLayout_2.addWidget(self.button_stop_logging)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 510, 551, 51))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.tuning_apply_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.tuning_apply_layout.setContentsMargins(0, 0, 0, 0)
        self.tuning_apply_layout.setObjectName("tuning_apply_layout")
        self.button_send_default_tuning = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.button_send_default_tuning.setEnabled(True)
        self.button_send_default_tuning.setObjectName("button_send_default_tuning")
        self.tuning_apply_layout.addWidget(self.button_send_default_tuning)
        self.button_send_custom_tuning = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.button_send_custom_tuning.setEnabled(True)
        self.button_send_custom_tuning.setObjectName("button_send_custom_tuning")
        self.tuning_apply_layout.addWidget(self.button_send_custom_tuning)
        self.parameter_list = QtWidgets.QListView(self.centralwidget)
        self.parameter_list.setGeometry(QtCore.QRect(260, 340, 299, 61))
        self.parameter_list.setObjectName("parameter_list")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 580, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Poldrone APQP PID Tuning Utility"))
        self.label_sys_in.setText(_translate("MainWindow", "Reference value:"))
        self.var_sysin.setText(_translate("MainWindow", "__sys_input__"))
        self.label_sys_out.setText(_translate("MainWindow", "Actual value:"))
        self.var_sysout.setText(_translate("MainWindow", "__sys_output__"))
        self.var_regerror.setText(_translate("MainWindow", "__sys_regerror__"))
        self.label_reg_error.setText(_translate("MainWindow", "Regulation error:"))
        self.label_D.setText(_translate("MainWindow", "Der. Gain (D)"))
        self.label_P.setText(_translate("MainWindow", "Prop. Gain (P)"))
        self.label_I.setText(_translate("MainWindow", "Int. Gain (I)"))
        self.button_send_velocity_update.setText(_translate("MainWindow", "Change Tuned Movement Axis"))
        self.label_monit.setText(_translate("MainWindow", "MONIT:"))
        self.var_monit.setText(_translate("MainWindow", "__monit__"))
        self.button_start_logging.setText(_translate("MainWindow", "Start Logging"))
        self.button_stop_logging.setText(_translate("MainWindow", "Stop Logging "))
        self.button_send_default_tuning.setText(_translate("MainWindow", "Set default tuning values"))
        self.button_send_custom_tuning.setText(_translate("MainWindow", "Set tuning values defined above"))



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())

    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    sys.exit(app.exec_())
